export interface Country {
  code: string; // ISO
  name: string;
  dial: string; // kode telepon
  flag: string; // emoji bendera
}

/** Daftar negara (kode telepon) — mencakup semua benua. Indonesia default. */
export const COUNTRIES: Country[] = [
  { code: "ID", name: "Indonesia", dial: "+62", flag: "🇮🇩" },
  { code: "MY", name: "Malaysia", dial: "+60", flag: "🇲🇾" },
  { code: "SG", name: "Singapura", dial: "+65", flag: "🇸🇬" },
  { code: "TH", name: "Thailand", dial: "+66", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", dial: "+84", flag: "🇻🇳" },
  { code: "PH", name: "Filipina", dial: "+63", flag: "🇵🇭" },
  { code: "BN", name: "Brunei", dial: "+673", flag: "🇧🇳" },
  { code: "KH", name: "Kamboja", dial: "+855", flag: "🇰🇭" },
  { code: "MM", name: "Myanmar", dial: "+95", flag: "🇲🇲" },
  { code: "TL", name: "Timor Leste", dial: "+670", flag: "🇹🇱" },
  { code: "IN", name: "India", dial: "+91", flag: "🇮🇳" },
  { code: "PK", name: "Pakistan", dial: "+92", flag: "🇵🇰" },
  { code: "BD", name: "Bangladesh", dial: "+880", flag: "🇧🇩" },
  { code: "CN", name: "Tiongkok", dial: "+86", flag: "🇨🇳" },
  { code: "JP", name: "Jepang", dial: "+81", flag: "🇯🇵" },
  { code: "KR", name: "Korea Selatan", dial: "+82", flag: "🇰🇷" },
  { code: "TW", name: "Taiwan", dial: "+886", flag: "🇹🇼" },
  { code: "HK", name: "Hong Kong", dial: "+852", flag: "🇭🇰" },
  { code: "SA", name: "Arab Saudi", dial: "+966", flag: "🇸🇦" },
  { code: "AE", name: "Uni Emirat Arab", dial: "+971", flag: "🇦🇪" },
  { code: "QA", name: "Qatar", dial: "+974", flag: "🇶🇦" },
  { code: "TR", name: "Turki", dial: "+90", flag: "🇹🇷" },
  { code: "EG", name: "Mesir", dial: "+20", flag: "🇪🇬" },
  { code: "ZA", name: "Afrika Selatan", dial: "+27", flag: "🇿🇦" },
  { code: "NG", name: "Nigeria", dial: "+234", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", dial: "+254", flag: "🇰🇪" },
  { code: "GB", name: "Inggris", dial: "+44", flag: "🇬🇧" },
  { code: "IE", name: "Irlandia", dial: "+353", flag: "🇮🇪" },
  { code: "FR", name: "Prancis", dial: "+33", flag: "🇫🇷" },
  { code: "DE", name: "Jerman", dial: "+49", flag: "🇩🇪" },
  { code: "NL", name: "Belanda", dial: "+31", flag: "🇳🇱" },
  { code: "ES", name: "Spanyol", dial: "+34", flag: "🇪🇸" },
  { code: "IT", name: "Italia", dial: "+39", flag: "🇮🇹" },
  { code: "PT", name: "Portugal", dial: "+351", flag: "🇵🇹" },
  { code: "SE", name: "Swedia", dial: "+46", flag: "🇸🇪" },
  { code: "NO", name: "Norwegia", dial: "+47", flag: "🇳🇴" },
  { code: "RU", name: "Rusia", dial: "+7", flag: "🇷🇺" },
  { code: "PL", name: "Polandia", dial: "+48", flag: "🇵🇱" },
  { code: "US", name: "Amerika Serikat", dial: "+1", flag: "🇺🇸" },
  { code: "CA", name: "Kanada", dial: "+1", flag: "🇨🇦" },
  { code: "MX", name: "Meksiko", dial: "+52", flag: "🇲🇽" },
  { code: "BR", name: "Brasil", dial: "+55", flag: "🇧🇷" },
  { code: "AR", name: "Argentina", dial: "+54", flag: "🇦🇷" },
  { code: "CL", name: "Chili", dial: "+56", flag: "🇨🇱" },
  { code: "AU", name: "Australia", dial: "+61", flag: "🇦🇺" },
  { code: "NZ", name: "Selandia Baru", dial: "+64", flag: "🇳🇿" },
];
